Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # --- Server ---
  config.vm.define "adiaz-ufS" do |server|
    server.vm.hostname = "adiaz-ufS"
    #server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "private_network", ip: "192.168.56.110", name: "VirtualBox Host-Only Ethernet Adapter #2"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # K3s Server
    server.vm.provision "shell", path: "scripts/k3s-server.sh"
  end

  # --- Worker ---
  config.vm.define "alaparicSW" do |worker|
    worker.vm.hostname = "alaparicSW"
    #worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.network "private_network", ip: "192.168.56.111", name: "VirtualBox Host-Only Ethernet Adapter #2"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # K3s Worker
    worker.vm.provision "shell", path: "scripts/k3s-worker.sh", args: ["192.168.56.110"]
  end
end
